using System;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Reflections
{
    public static class MethodInfoExtensions
    {
        public static bool IsAutoGenerated(this MethodInfo element)
        {
            return element.GetCustomAttributes<CompilerGeneratedAttribute>(true).Any();
        }

        public static bool IsNotAutoGenerated(this MethodInfo element)
        {
            return !IsAutoGenerated(element);
        }

        public static bool IsNotOverride(this MethodInfo element)
        {
            return !IsOverride(element);
        }

        public static bool IsOverride(this MethodInfo element)
        {
            if (element == null)
            {
                throw new ArgumentNullException("element", "methodInfo may not be null.");
            }

            var declaringType = element.DeclaringType;
            var baseDefinitionType = element.GetBaseDefinition().DeclaringType;
            return declaringType != baseDefinitionType;
        }
    }
}